# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

alphpow <- function(x, mat) {
    .Call(`_cpmgee_alphpow`, x, mat)
}

cmat <- function(ctimes, alpha, corrmod, diffmeth, h) {
    .Call(`_cpmgee_cmat`, ctimes, alpha, corrmod, diffmeth, h)
}

fixmod <- function(mod, coeffs, X) {
    .Call(`_cpmgee_fixmod`, mod, coeffs, X)
}

mat_add <- function(a, b) {
    .Call(`_cpmgee_mat_add`, a, b)
}

mat_minus <- function(a, b) {
    .Call(`_cpmgee_mat_minus`, a, b)
}

ordgee <- function(mod, icormat, X, ctimes, categories, omaxit, otol) {
    .Call(`_cpmgee_ordgee`, mod, icormat, X, ctimes, categories, omaxit, otol)
}

smat <- function(coeff) {
    .Call(`_cpmgee_smat`, coeff)
}

